[project]
name = "test-workspace"
pyblade_version = "0.3.0"

[stack]
framework = "django"
css_framework = "tailwindcss"
css_framework_version = "4"

[paths]
root = "test-workspace"
# settings = "core/settings.py"